# Generated by Django 4.2.5 on 2023-09-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='category_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suplier_name',
            new_name='supplier_name',
        ),
    ]
